# Configurações do HubSpot
hubspot.client_id=a2bbe529-d6e9-4fd2-9bbf-ba83f1151a86
hubspot.client_secret=63ba6af1-149b-4460-99d3-dfe96a1088e6
hubspot.redirect_uri=http://localhost:8080/api/auth/callback
hubspot.scopes=crm.objects.contacts.write crm.objects.contacts.read oauth
hubspot.access_token= SEU_ACCESS_TOKEN
